echo "$light_green Node.js has been installed in the following version: $reset_colour"
echo " $(node --version)"
echo ""
echo "$light_green Npm has been installed in the following version: $reset_colour"
echo " $(npm --version)"
