echo "$success Node.js has been installed in the following version: $reset_colour"
echo " $(node --version)"
echo ""
echo "$success Npm has been installed in the following version: $reset_colour"
echo " $(npm --version)"
